"""Initial migration.

Revision ID: 1d0b38f248b9
Revises: 
Create Date: 2024-06-29 18:34:44.526302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d0b38f248b9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('genre', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('director', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('release_date', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('rating', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.drop_column('rating')
        batch_op.drop_column('release_date')
        batch_op.drop_column('director')
        batch_op.drop_column('genre')

    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('email', sa.VARCHAR(length=100), nullable=True),
    sa.Column('password', sa.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
